import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Playfair_Display } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";



const plusJakarta = Plus_Jakarta_Sans ({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"]
})

const playfairDisplay = Playfair_Display ({
  variable: "--font-playfair-display",
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        >   
         <Navbar />
         <main className="relative z-0 px-3 bg-zinc-50 font-sans dark:bg-white">
        {children}
         </main>

      </body>
    </html>
  );
}
